Document: libappindicator-ayatana-compat
Title: Debian libappindicator-ayatana-compat Manual
Author: <insert document author here>
Abstract: This manual describes what libappindicator-ayatana-compat is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libappindicator-ayatana-compat/libappindicator-ayatana-compat.sgml.gz

Format: postscript
Files: /usr/share/doc/libappindicator-ayatana-compat/libappindicator-ayatana-compat.ps.gz

Format: text
Files: /usr/share/doc/libappindicator-ayatana-compat/libappindicator-ayatana-compat.text.gz

Format: HTML
Index: /usr/share/doc/libappindicator-ayatana-compat/html/index.html
Files: /usr/share/doc/libappindicator-ayatana-compat/html/*.html
